### ISSUE TITLE
Attempting horizontal scroll

### ISSUE THREAD

**Issue by wusgitaccount** [wusgitaccount/wishywashyworld#1]
I've tried following a tutorial that required me to add a mousewheel https://github.com/jquery/jquery-mousewheel but not so sure how to use it. 
This is the js from the forum:
$(function() {
   $("body").mousewheel(function(evt, chg) {
      this.scrollLeft -= (chg * 50); //need a value to speed up the change
      evt.preventDefault();
   });
});

And the script reference:
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="/js/jquery.mousewheel.js"></script>

**Comment by sehsarah** [comment]
Something like this seems more like the buzz https://css-tricks.com/how-to-create-a-horizontally-scrolling-site/

This is the codepen at the end of the tutorial https://codepen.io/chriscoyier/pen/VRMpgw

**Comment by wusgitaccount** [comment]
Thank you!! I've got it working now kinda- just gotta clean it up cause it looks like it was designed for a vertically scrolling page now <3
