### ISSUE TITLE
Table width not flexible

### ISSUE THREAD

**Issue by wusgitaccount** [wusgitaccount/wishywashyworld#5]
![Capture](https://user-images.githubusercontent.com/53881620/67347298-2374b600-f59e-11e9-897c-186034aa9ab8.PNG)
Hiii 
To make the horizontal scroll, I had to set a width for my main page container, ww-page, so I set it to 600px per cell. I'm trying to make my title bigger now and it can only go as big as 600px before it overlaps under the other cells. Anyway to show the entire sequence?

**Comment by sehsarah** [comment]
What do you mean by entire sequence? Do you want the cell to grow bigger to accomodate the larger title or do you wan the title to overlap into the next cell?

Maybe show me what you want it to look like vs. what it looks like now

**Comment by sehsarah** [comment]
Or is your problem about responsive sizing?

**Comment by wusgitaccount** [comment]
I want the cell to grow bigger to accommodate the larger title, however the table width is set to 600px- as per the article, don't think the problem is with responsive sizing as the title always cuts off at that point. 

.ww-page {
  width: 600px;
  overflow: hidden;
  position:relative;
}
This is what is was before at 100%, so it fits within the cell but I want it to be bigger. 
![image](https://user-images.githubusercontent.com/53881620/67348851-b6175400-f5a2-11e9-802e-fa769cdcee39.png)

**Comment by sehsarah** [comment]
Sounds like it could be fixed with media queries, related to https://github.com/wusgitaccount/wishywashyworld/issues/4  - @ellysmlly might have some input

**Comment by sehsarah** [comment]
- Might not need the JS wraps to add the `td`
- add the td elements directly in the html
- add a custom class to the 1st cell and target just that class/cell to be bigger than 600px
